### ISSUE TITLE
Make Night mode button more visible

### ISSUE THREAD

**Issue by shrx** [Gordon999/Pi-AutoGuider#6]
Right now, the "Night mode" indicator can be very hard to find, as it is not drawn like a regular button. The small "D" / "N" letter can easily be missed. Also, it is not clear that this letter acts as a button and not a passive indicator. I suggest the visibility and clarity of this button be improved.

**Comment by Gordon999** [comment]
I'll take a look at it. It may mean more buttons required, eg smaller, or a different layout.

**Comment by Gordon999** [comment]
added to version r8y3 if you want to try it.

**Comment by shrx** [comment]
Looks good 👍

**Comment by shrx** [comment]
Btw, it's not a good practice to upload whole new files to master named `program_version.py`. Instead, branches with version numbers or a "working"/"testing"/"develop" branch should be created, and when you are satisfied with the new additions, you merge the branch into master. All files should have the same name, i.e. `program.py`. This way, it can be seen more easily what has changed between commits; if you upload a new file and delete the old, github can't display the diffs between them. It is sufficient to keep the version number string inside the file, as you have already done.
More info here: http://programmers.stackexchange.com/questions/165725/git-branching-and-tagging-best-practices
And here: http://nvie.com/posts/a-successful-git-branching-model/

**Comment by Gordon999** [comment]
Thanks for the advice. I'm still learning, it all seems complicated to me !
