### ISSUE TITLE
ave variable

### ISSUE THREAD

**Issue by shrx** [Gordon999/Pi-AutoGuider#7]
The `ave` variable is set to 0 at the beginning of the code and then never changes.
Because of this, some of the code is redundant, for example:

```
if ttot > 1 and ave and aveon and acorrect > 0 and avevcor > 0 and ymax == avemax:
            acorrect = avevcor
```

will never execute because `ave` is always 0 (false). Do you plan to use this variable in the future, or should it be removed?

**Comment by Gordon999** [comment]
I will look at removing it, it was an attempt at averaging moves over several shots but didn't work as expected.

**Comment by Gordon999** [comment]
Removed in 8y4. Also found 'plot' has issues so pasted the old code for that section.
